/*
ULTIMA ATUALIZACAO: 2017.06
*/

FUNCTION ZE_TABUNIDADE()

   LOCAL aList := {}

   AAdd( aList, { "AMPOLA", "AMPOLA" } )
   AAdd( aList, { "BALDE", "BALDE" } )
   AAdd( aList, { "BANDEJ", "BANDEJA" } )
   AAdd( aList, { "BARRA", "BARRA" } )
   AAdd( aList, { "BISNAG", "BISNAGA" } )
   AAdd( aList, { "BLOCO", "BLOCO" } )
   AAdd( aList, { "BOBINA", "BOBINA" } )
   AAdd( aList, { "BOMB", "BOMBONA" } )
   AAdd( aList, { "CAPS", "CAPSULA" } )
   AAdd( aList, { "CART", "CARTELA" } )
   AAdd( aList, { "CENTO", "CENTO" } )
   AAdd( aList, { "CJ", "CONJUNTO" } )
   AAdd( aList, { "CM", "CENTIMETRO" } )
   AAdd( aList, { "CM2", "CENTIMETRO QUADRADO" } )
   AAdd( aList, { "CX", "CAIXA" } )
   AAdd( aList, { "CX2", "CAIXA COM 2 UNIDADES" } )
   AAdd( aList, { "CX3", "CAIXA COM 3 UNIDADES" } )
   AAdd( aList, { "CX5", "CAIXA COM 5 UNIDADES" } )
   AAdd( aList, { "CX10", "CAIXA COM 10 UNIDADES" } )
   AAdd( aList, { "CX15", "CAIXA COM 15 UNIDADES" } )
   AAdd( aList, { "CX20", "CAIXA COM 20 UNIDADES" } )
   AAdd( aList, { "CX25", "CAIXA COM 25 UNIDADES" } )
   AAdd( aList, { "CX50", "CAIXA COM 50 UNIDADES" } )
   AAdd( aList, { "CX100", "CAIXA COM 100 UNIDADES" } )
   AAdd( aList, { "DISP", "DISPLAY" } )
   AAdd( aList, { "DUZIA", "DUZIA" } )
   AAdd( aList, { "EMBAL", "EMBALAGEM" } )
   AAdd( aList, { "FARDO", "FARDO" } )
   AAdd( aList, { "FOLHA", "FOLHA" } )
   AAdd( aList, { "FRASCO", "FRASCO" } )
   AAdd( aList, { "GALAO", "GALAO" } )
   AAdd( aList, { "GF", "GARRAFA" } )
   AAdd( aList, { "GRAMAS", "GRAMAS" } )
   AAdd( aList, { "JOGO", "JOGO" } )
   AAdd( aList, { "KG", "QUILOGRAMA" } )
   AAdd( aList, { "KIT", "KIT" } )
   AAdd( aList, { "LATA", "LATA" } )
   AAdd( aList, { "LITRO", "LITRO" } )
   AAdd( aList, { "M", "METRO" } )
   AAdd( aList, { "M2", "METRO QUADRADO" } )
   AAdd( aList, { "M3", "METRO CUBICO" } )
   AAdd( aList, { "MILHEI", "MILHEIRO" } )
   AAdd( aList, { "ML", "MILILITRO" } )
   AAdd( aList, { "MWH", "MEGAWATT HORA" } )
   AAdd( aList, { "PACOTE", "PACOTE" } )
   AAdd( aList, { "PALETE", "PALETE" } )
   AAdd( aList, { "PARES", "PARES" } )
   AAdd( aList, { "PC", "PECA" } )
   AAdd( aList, { "POTE", "POTE" } )
   AAdd( aList, { "K", "QUILATE" } )
   AAdd( aList, { "RESMA", "RESMA" } )
   AAdd( aList, { "ROLO", "ROLO" } )
   AAdd( aList, { "SACO", "SACO" } )
   AAdd( aList, { "SACOLA", "SACOLA" } )
   AAdd( aList, { "TAMBOR", "TAMBOR" } )
   AAdd( aList, { "TANQUE", "TANQUE" } )
   AAdd( aList, { "TON", "TONELADA" } )
   AAdd( aList, { "TUBO", "TUBO" } )
   AAdd( aList, { "UNID", "UNIDADE" } )
   AAdd( aList, { "VASIL", "VASILHAME" } )
   AAdd( aList, { "VIDRO", "VIDRO" } )

   RETURN ALIST
