/*
ULTIMA ATUALIZACAO: 2017.06
*/

FUNCTION ZE_TABPAIS()

   LOCAL aList := {}

   AAdd( aList, { 132, "AFEGANISTAO" } )
   AAdd( aList, { 175, "ALBANIA, REPUBLICA  DA" } )
   AAdd( aList, { 200, "CURACAO" } )
   AAdd( aList, { 230, "ALEMANHA" } )
   AAdd( aList, { 310, "BURKINA FASO" } )
   AAdd( aList, { 370, "ANDORRA" } )
   AAdd( aList, { 400, "ANGOLA" } )
   AAdd( aList, { 418, "ANGUILLA" } )
   AAdd( aList, { 434, "ANTIGUA E BARBUDA" } )
   AAdd( aList, { 477, "ANTILHAS HOLANDESAS" } )
   AAdd( aList, { 531, "ARABIA SAUDITA" } )
   AAdd( aList, { 590, "ARGELIA" } )
   AAdd( aList, { 639, "ARGENTINA" } )
   AAdd( aList, { 647, "ARMENIA, REPUBLICA DA" } )
   AAdd( aList, { 655, "ARUBA" } )
   AAdd( aList, { 698, "AUSTRALIA" } )
   AAdd( aList, { 728, "AUSTRIA" } )
   AAdd( aList, { 736, "AZERBAIJAO, REPUBLICA DO" } )
   AAdd( aList, { 779, "BAHAMAS, ILHAS" } )
   AAdd( aList, { 809, "BAHREIN, ILHAS" } )
   AAdd( aList, { 817, "BANGLADESH" } )
   AAdd( aList, { 833, "BARBADOS" } )
   AAdd( aList, { 850, "BELARUS, REPUBLICA DA" } )
   AAdd( aList, { 876, "BELGICA" } )
   AAdd( aList, { 884, "BELIZE" } )
   AAdd( aList, { 906, "BERMUDAS" } )
   AAdd( aList, { 930, "MIANMAR (BIRMANIA)" } )
   AAdd( aList, { 973, "BOLIVIA, ESTADO PLURINACIONAL DA" } )
   AAdd( aList, { 981, "BOSNIA-HERZEGOVINA (REPUBLICA DA)" } )
   AAdd( aList, { 1015, "BOTSUANA" } )
   AAdd( aList, { 1058, "BRASIL" } )
   AAdd( aList, { 1082, "BRUNEI" } )
   AAdd( aList, { 1112, "BULGARIA, REPUBLICA DA" } )
   AAdd( aList, { 1155, "BURUNDI" } )
   AAdd( aList, { 1198, "BUTAO" } )
   AAdd( aList, { 1279, "CABO VERDE, REPUBLICA DE" } )
   AAdd( aList, { 1376, "CAYMAN, ILHAS" } )
   AAdd( aList, { 1414, "CAMBOJA" } )
   AAdd( aList, { 1457, "CAMAROES" } )
   AAdd( aList, { 1490, "CANADA" } )
   AAdd( aList, { 1504, "GUERNSEY, ILHA DO CANAL (INCLUI ALDERNEY E SARK)" } )
   AAdd( aList, { 1508, "JERSEY, ILHA DO CANAL" } )
   AAdd( aList, { 1511, "CANARIAS, ILHAS" } )
   AAdd( aList, { 1538, "CAZAQUISTAO, REPUBLICA DO" } )
   AAdd( aList, { 1546, "CATAR" } )
   AAdd( aList, { 1589, "CHILE" } )
   AAdd( aList, { 1600, "CHINA, REPUBLICA POPULAR" } )
   AAdd( aList, { 1619, "FORMOSA (TAIWAN)" } )
   AAdd( aList, { 1635, "CHIPRE" } )
   AAdd( aList, { 1651, "COCOS(KEELING),ILHAS" } )
   AAdd( aList, { 1694, "COLOMBIA" } )
   AAdd( aList, { 1732, "COMORES, ILHAS" } )
   AAdd( aList, { 1775, "CONGO" } )
   AAdd( aList, { 1830, "COOK, ILHAS" } )
   AAdd( aList, { 1872, "COREIA (DO NORTE), REP.POP.DEMOCRATICA" } )
   AAdd( aList, { 1902, "COREIA (DO SUL), REPUBLICA DA" } )
   AAdd( aList, { 1937, "COSTA DO MARFIM" } )
   AAdd( aList, { 1953, "CROACIA (REPUBLICA DA)" } )
   AAdd( aList, { 1961, "COSTA RICA" } )
   AAdd( aList, { 1988, "COVEITE" } )
   AAdd( aList, { 1996, "CUBA" } )
   AAdd( aList, { 2291, "BENIN" } )
   AAdd( aList, { 2321, "DINAMARCA" } )
   AAdd( aList, { 2356, "DOMINICA,ILHA" } )
   AAdd( aList, { 2399, "EQUADOR" } )
   AAdd( aList, { 2402, "EGITO" } )
   AAdd( aList, { 2437, "ERITREIA" } )
   AAdd( aList, { 2445, "EMIRADOS ARABES UNIDOS" } )
   AAdd( aList, { 2453, "ESPANHA" } )
   AAdd( aList, { 2461, "ESLOVENIA, REPUBLICA DA" } )
   AAdd( aList, { 2470, "ESLOVACA, REPUBLICA" } )
   AAdd( aList, { 2496, "ESTADOS UNIDOS" } )
   AAdd( aList, { 2518, "ESTONIA, REPUBLICA DA" } )
   AAdd( aList, { 2534, "ETIOPIA" } )
   AAdd( aList, { 2550, "FALKLAND (ILHAS MALVINAS)" } )
   AAdd( aList, { 2593, "FEROE, ILHAS" } )
   AAdd( aList, { 2674, "FILIPINAS" } )
   AAdd( aList, { 2712, "FINLANDIA" } )
   AAdd( aList, { 2755, "FRANCA" } )
   AAdd( aList, { 2810, "GABAO" } )
   AAdd( aList, { 2852, "GAMBIA" } )
   AAdd( aList, { 2895, "GANA" } )
   AAdd( aList, { 2917, "GEORGIA, REPUBLICA DA" } )
   AAdd( aList, { 2933, "GIBRALTAR" } )
   AAdd( aList, { 2976, "GRANADA" } )
   AAdd( aList, { 3018, "GRECIA" } )
   AAdd( aList, { 3050, "GROENLANDIA" } )
   AAdd( aList, { 3093, "GUADALUPE" } )
   AAdd( aList, { 3131, "GUAM" } )
   AAdd( aList, { 3174, "GUATEMALA" } )
   AAdd( aList, { 3255, "GUIANA FRANCESA" } )
   AAdd( aList, { 3298, "GUINE" } )
   AAdd( aList, { 3310, "GUINE-EQUATORIAL" } )
   AAdd( aList, { 3344, "GUINE-BISSAU" } )
   AAdd( aList, { 3379, "GUIANA" } )
   AAdd( aList, { 3417, "HAITI" } )
   AAdd( aList, { 3450, "HONDURAS" } )
   AAdd( aList, { 3514, "HONG KONG" } )
   AAdd( aList, { 3557, "HUNGRIA, REPUBLICA DA" } )
   AAdd( aList, { 3573, "IEMEN" } )
   AAdd( aList, { 3595, "MAN, ILHA DE" } )
   AAdd( aList, { 3611, "INDIA" } )
   AAdd( aList, { 3654, "INDONESIA" } )
   AAdd( aList, { 3697, "IRAQUE" } )
   AAdd( aList, { 3727, "IRA, REPUBLICA ISLAMICA DO" } )
   AAdd( aList, { 3751, "IRLANDA" } )
   AAdd( aList, { 3794, "ISLANDIA" } )
   AAdd( aList, { 3832, "ISRAEL" } )
   AAdd( aList, { 3867, "ITALIA" } )
   AAdd( aList, { 3913, "JAMAICA" } )
   AAdd( aList, { 3964, "JOHNSTON, ILHAS" } )
   AAdd( aList, { 3999, "JAPAO" } )
   AAdd( aList, { 4030, "JORDANIA" } )
   AAdd( aList, { 4111, "KIRIBATI" } )
   AAdd( aList, { 4200, "LAOS, REP.POP.DEMOCR.DO" } )
   AAdd( aList, { 4235, "LEBUAN,ILHAS" } )
   AAdd( aList, { 4260, "LESOTO" } )
   AAdd( aList, { 4278, "LETONIA, REPUBLICA DA" } )
   AAdd( aList, { 4316, "LIBANO" } )
   AAdd( aList, { 4340, "LIBERIA" } )
   AAdd( aList, { 4383, "LIBIA" } )
   AAdd( aList, { 4405, "LIECHTENSTEIN" } )
   AAdd( aList, { 4421, "LITUANIA, REPUBLICA DA" } )
   AAdd( aList, { 4456, "LUXEMBURGO" } )
   AAdd( aList, { 4472, "MACAU" } )
   AAdd( aList, { 4499, "MACEDONIA, ANT.REP.IUGOSLAVA" } )
   AAdd( aList, { 4502, "MADAGASCAR" } )
   AAdd( aList, { 4525, "MADEIRA, ILHA DA" } )
   AAdd( aList, { 4553, "MALASIA" } )
   AAdd( aList, { 4588, "MALAVI" } )
   AAdd( aList, { 4618, "MALDIVAS" } )
   AAdd( aList, { 4642, "MALI" } )
   AAdd( aList, { 4677, "MALTA" } )
   AAdd( aList, { 4723, "MARIANAS DO NORTE" } )
   AAdd( aList, { 4740, "MARROCOS" } )
   AAdd( aList, { 4766, "MARSHALL,ILHAS" } )
   AAdd( aList, { 4774, "MARTINICA" } )
   AAdd( aList, { 4855, "MAURICIO" } )
   AAdd( aList, { 4880, "MAURITANIA" } )
   AAdd( aList, { 4885, "MAYOTTE (ILHAS FRANCESAS)" } )
   AAdd( aList, { 4901, "MIDWAY, ILHAS" } )
   AAdd( aList, { 4936, "MEXICO" } )
   AAdd( aList, { 4944, "MOLDAVIA, REPUBLICA DA" } )
   AAdd( aList, { 4952, "MONACO" } )
   AAdd( aList, { 4979, "MONGOLIA" } )
   AAdd( aList, { 4985, "MONTENEGRO" } )
   AAdd( aList, { 4995, "MICRONESIA" } )
   AAdd( aList, { 5010, "MONTSERRAT,ILHAS" } )
   AAdd( aList, { 5053, "MOCAMBIQUE" } )
   AAdd( aList, { 5070, "NAMIBIA" } )
   AAdd( aList, { 5088, "NAURU" } )
   AAdd( aList, { 5118, "CHRISTMAS,ILHA (NAVIDAD)" } )
   AAdd( aList, { 5177, "NEPAL" } )
   AAdd( aList, { 5215, "NICARAGUA" } )
   AAdd( aList, { 5258, "NIGER" } )
   AAdd( aList, { 5282, "NIGERIA" } )
   AAdd( aList, { 5312, "NIUE,ILHA" } )
   AAdd( aList, { 5355, "NORFOLK,ILHA" } )
   AAdd( aList, { 5380, "NORUEGA" } )
   AAdd( aList, { 5428, "NOVA CALEDONIA" } )
   AAdd( aList, { 5452, "PAPUA NOVA GUINE" } )
   AAdd( aList, { 5487, "NOVA ZELANDIA" } )
   AAdd( aList, { 5517, "VANUATU" } )
   AAdd( aList, { 5568, "OMA" } )
   AAdd( aList, { 5665, "PACIFICO,ILHAS DO (POSSESSAO DOS EUA)" } )
   AAdd( aList, { 5738, "PAISES BAIXOS (HOLANDA)" } )
   AAdd( aList, { 5754, "PALAU" } )
   AAdd( aList, { 5762, "PAQUISTAO" } )
   AAdd( aList, { 5780, "PALESTINA" } )
   AAdd( aList, { 5800, "PANAMA" } )
   AAdd( aList, { 5860, "PARAGUAI" } )
   AAdd( aList, { 5894, "PERU" } )
   AAdd( aList, { 5932, "PITCAIRN,ILHA" } )
   AAdd( aList, { 5991, "POLINESIA FRANCESA" } )
   AAdd( aList, { 6033, "POLONIA, REPUBLICA DA" } )
   AAdd( aList, { 6076, "PORTUGAL" } )
   AAdd( aList, { 6114, "PORTO RICO" } )
   AAdd( aList, { 6238, "QUENIA" } )
   AAdd( aList, { 6254, "QUIRGUIZ, REPUBLICA" } )
   AAdd( aList, { 6289, "REINO UNIDO" } )
   AAdd( aList, { 6408, "REPUBLICA CENTRO-AFRICANA" } )
   AAdd( aList, { 6475, "REPUBLICA DOMINICANA" } )
   AAdd( aList, { 6602, "REUNIAO, ILHA" } )
   AAdd( aList, { 6653, "ZIMBABUE" } )
   AAdd( aList, { 6700, "ROMENIA" } )
   AAdd( aList, { 6750, "RUANDA" } )
   AAdd( aList, { 6769, "RUSSIA, FEDERACAO DA" } )
   AAdd( aList, { 6777, "SALOMAO, ILHAS" } )
   AAdd( aList, { 6858, "SAARA OCIDENTAL" } )
   AAdd( aList, { 6874, "EL SALVADOR" } )
   AAdd( aList, { 6904, "SAMOA" } )
   AAdd( aList, { 6912, "SAMOA AMERICANA" } )
   AAdd( aList, { 6955, "SAO CRISTOVAO E NEVES,ILHAS" } )
   AAdd( aList, { 6971, "SAN MARINO" } )
   AAdd( aList, { 7005, "SAO PEDRO E MIQUELON" } )
   AAdd( aList, { 7056, "SAO VICENTE E GRANADINAS" } )
   AAdd( aList, { 7102, "SANTA HELENA" } )
   AAdd( aList, { 7153, "SANTA LUCIA" } )
   AAdd( aList, { 7200, "SAO TOME E PRINCIPE, ILHAS" } )
   AAdd( aList, { 7285, "SENEGAL" } )
   AAdd( aList, { 7315, "SEYCHELLES" } )
   AAdd( aList, { 7358, "SERRA LEOA" } )
   AAdd( aList, { 7370, "SERVIA" } )
   AAdd( aList, { 7412, "CINGAPURA" } )
   AAdd( aList, { 7447, "SIRIA, REPUBLICA ARABE DA" } )
   AAdd( aList, { 7480, "SOMALIA" } )
   AAdd( aList, { 7501, "SRI LANKA" } )
   AAdd( aList, { 7544, "SUAZILANDIA" } )
   AAdd( aList, { 7560, "AFRICA DO SUL" } )
   AAdd( aList, { 7595, "SUDAO" } )
   AAdd( aList, { 7600, "SUDAO DO SUL" } )
   AAdd( aList, { 7641, "SUECIA" } )
   AAdd( aList, { 7676, "SUICA" } )
   AAdd( aList, { 7706, "SURINAME" } )
   AAdd( aList, { 7722, "TADJIQUISTAO, REPUBLICA DO" } )
   AAdd( aList, { 7765, "TAILANDIA" } )
   AAdd( aList, { 7803, "TANZANIA, REP.UNIDA DA" } )
   AAdd( aList, { 7820, "TERRITORIO BRIT.OC.INDICO" } )
   AAdd( aList, { 7838, "DJIBUTI" } )
   AAdd( aList, { 7889, "CHADE" } )
   AAdd( aList, { 7919, "TCHECA, REPUBLICA" } )
   AAdd( aList, { 7951, "TIMOR LESTE" } )
   AAdd( aList, { 8001, "TOGO" } )
   AAdd( aList, { 8052, "TOQUELAU,ILHAS" } )
   AAdd( aList, { 8109, "TONGA" } )
   AAdd( aList, { 8150, "TRINIDAD E TOBAGO" } )
   AAdd( aList, { 8206, "TUNISIA" } )
   AAdd( aList, { 8230, "TURCAS E CAICOS,ILHAS" } )
   AAdd( aList, { 8249, "TURCOMENISTAO, REPUBLICA DO" } )
   AAdd( aList, { 8273, "TURQUIA" } )
   AAdd( aList, { 8281, "TUVALU" } )
   AAdd( aList, { 8311, "UCRANIA" } )
   AAdd( aList, { 8338, "UGANDA" } )
   AAdd( aList, { 8451, "URUGUAI" } )
   AAdd( aList, { 8478, "UZBEQUISTAO, REPUBLICA DO" } )
   AAdd( aList, { 8486, "VATICANO, EST.DA CIDADE DO" } )
   AAdd( aList, { 8508, "VENEZUELA" } )
   AAdd( aList, { 8583, "VIETNA" } )
   AAdd( aList, { 8630, "VIRGENS,ILHAS (BRITANICAS)" } )
   AAdd( aList, { 8664, "VIRGENS,ILHAS (E.U.A.)" } )
   AAdd( aList, { 8702, "FIJI" } )
   AAdd( aList, { 8737, "WAKE, ILHA" } )
   AAdd( aList, { 8885, "CONGO, REPUBLICA DEMOCRATICA DO" } )
   AAdd( aList, { 8907, "ZAMBIA" } )

   RETURN ALIST
