#include "..\prg\getsys.prg"
#include "..\prg\errorsys.prg"

REQUEST RunModule

#include "hbclass.ch"

FUNCTION appversaoexe(); RETURN "1"
FUNCTION appodbcmysql(); RETURN 3
FUNCTION myuser();       RETURN ""
FUNCTION mypassword();   RETURN ""
FUNCTION ismyserialhd(); RETURN .F.
FUNCTION criptografa( cText ) ; RETURN cText
FUNCTION descriptografa( cText ); RETURN cText
CREATE CLASS jplicmovclass
   METHOD ShowVencidas() INLINE NIL
   ENDCLASS

procedure appcnmysqllocal
procedure criazip
procedure appcnserverjpa
procedure jpeglogotipo

procedure ctplanoclass
procedure jpcadas1class
procedure jpmdfcabclass
procedure jpmotoriclass
procedure jpveiculclass
procedure jpnfbaseclass
procedure ctloteslass
procedure jpimposclass
procedure jpforpagclass
procedure jpagendaclass
procedure jptransaclass
procedure jppediclass
procedure jpitemclass
procedure appcnjosequintas
procedure jpvendedclass
procedure nomecertificado
procedure jpalogerro
procedure etcmaio
procedure pupdateexedown
procedure menuacessos
procedure enviaemail
procedure ctlancaclass
procedure recalculasinteticas
procedure estlancclass
procedure pedi0290
procedure pnfe0020
procedure pedixml
procedure pedixml2
procedure jpsite
procedure pedi0200
procedure pedi0210
procedure pedi0220
procedure pedi0280
procedure pedi0230
procedure pedi0300
procedure pteshar
procedure psit0040
procedure ptes0120
procedure ctlotesclass
procedure pnot0170
procedure pcontimpexcel
procedure ptes0060
procedure pnot0200
procedure pbug0020
procedure pupdateexeup
procedure puti0020
procedure puti0022
procedure pedi0260
procedure pedi0240
procedure psetupempresa
procedure pjpsite
procedure pjpforpag
procedure pjpnfbase
procedure pjptransa
procedure pnfe0010
procedure pnfe0050
procedure ptes0130
procedure pnfe0060
procedure pnfe0070
procedure pedi0150
procedure pedicfin
procedure pretitau
procedure pedi0010
procedure pedi0040
procedure pedi0270
procedure pcontimpsped
procedure pfiscsintegra
procedure pjpagenda
procedure pjpcadas1
procedure pjpcadas1b
procedure pjpempre
procedure pcontlancpad
procedure pjplicmov
procedure ljplicmov
procedure pcontcontas
procedure pjpitem
procedure pjpitemb
procedure pjpcadas3
procedure pjpvended
procedure pjppromix
procedure pjpveicul
procedure pjpmotori
procedure pedi0060
procedure pfiscrel0030
procedure pfiscrel0010
procedure pfiscrel0040
procedure pfiscrel0100
procedure pfiscrel0110
procedure pfiscrel0120
procedure pfiscrel0050
procedure ljpforpag
procedure ljpcadas
procedure pjpanpmov
procedure pcontsped
procedure pfiscsped
procedure ljpcadas3
procedure pcontrel0520
procedure pcontrel0210
procedure pcontrel0010
procedure pcontrel0310
procedure pcontrel0320
procedure pcontrel0550
procedure pcontrel0530
procedure pcontrel0385
procedure pcontrel0470
procedure pcontrel0140
procedure pcontrel0080
procedure pleisrelimposto
procedure ljpitem
procedure ljpestoqb
procedure ljpestoqc
procedure pest0120
procedure pjpfisicab
procedure pfin0120
procedure pfin0130
procedure pfin0140
procedure pfin0150
procedure pfin0020
procedure pcontrel0360
procedure pcontrel0270
procedure pcontrel0380
procedure pcontrel0300
procedure pcontrel0330
procedure pfiscrel0140
procedure pfiscrel0130
procedure pfiscrel0080
procedure pnot0080
procedure pnot0250
procedure pnot0090
procedure pnot0100
procedure pnot0101
procedure pnot0102
procedure pnot0120
procedure pnot0130
procedure pnot0145
procedure pnot0150
procedure pnot0160
procedure pnot0190
procedure pBancoRelExtrato
procedure pBancoRelSaldo
procedure pBancoRelCCusto
procedure ljpestoqa
procedure pBancoGrafResumo
procedure pfin0030
procedure pfin0035
procedure pfin0010
procedure pcontlancinclui
procedure pcontlanclote
procedure pcontlancaltera
procedure pcontfecha
procedure pcontsintetica
procedure pcontrecalculo
procedure pfiscentradas
procedure pfiscsaidas
procedure pleisimposto
procedure ljppedi
procedure jpacfg
procedure pestlanca2
procedure pestlanca1
procedure pestentfor
procedure pbar0010
procedure pbar0040
procedure pjpfisicaa
procedure pestvalest
procedure pnot0260
procedure pBancoLanca
procedure pBancoConsolida
procedure pBancoComparaMes
procedure pBancoGraficoMes
procedure pBancoCCusto
procedure pfin0045
procedure pnot0060
procedure pda0010
procedure pcteinut
procedure pnfeinut
procedure ppre0010
procedure ppre0030
procedure ppre0020
procedure llpreco
procedure pnot0213
procedure pnot0214
procedure pnot0220
procedure pBancoSaldo
procedure pBancoGera
procedure pfin0040
procedure psetuplibera
procedure p0600ped
procedure pnot0010
procedure pnot0020
procedure pnot0030
procedure pnot0050
procedure pjpmdf
procedure pnot0070
procedure pnot0040
procedure pcteCancel
procedure ze_netioopen
procedure ze_netioclose
procedure jpnotaclass
procedure jpegBancoItau
procedure UltimaEntradaItem
procedure UltimaSaidaItem
procedure CustoContabilItem
