#include "..\prg\getsys.prg"
#include "..\prg\errorsys.prg"

REQUEST RunModule

#include "hbclass.ch"

FUNCTION appversaoexe(); RETURN "1"
FUNCTION appodbcmysql(); RETURN 3
FUNCTION myuser();       RETURN ""
FUNCTION mypassword();   RETURN ""
FUNCTION ismyserialhd(); RETURN .F.
FUNCTION pw_criptografa( cText ) ; RETURN cText
FUNCTION pw_descriptografa( cText ); RETURN cText
CREATE CLASS jplicmovclass
   METHOD ShowVencidas() INLINE NIL
   ENDCLASS

procedure appcnmysqllocal
procedure criazip
procedure appcnserverjpa
procedure jpeglogotipo

procedure ctplanoclass
procedure jpcadas1class
procedure jpmdfcabclass
procedure jpmotoriclass
procedure jpveiculclass
procedure jpnfbaseclass
procedure ctloteslass
procedure jpimposclass
procedure jpforpagclass
procedure jpagendaclass
procedure jptransaclass
procedure jppediclass
procedure jpitemclass
procedure appcnjosequintas
procedure jpvendedclass
procedure nomecertificado
procedure jpalogerro
procedure etcmaio
procedure pupdateexedown
procedure menuacessos
procedure enviaemail
procedure ctlancaclass
procedure recalculasinteticas
procedure estlancclass
procedure pedi0290
procedure pnfeServer
procedure pedixml
procedure pedixml2
procedure jpsite
procedure pedi0200
procedure pedi0210
procedure pedi0220
procedure pedi0280
procedure pedi0230
procedure pGeralHtmlPedido
procedure pNotaVendas
procedure ctlotesclass
procedure pNotaConsProd
procedure pcontimpexcel
procedure pNotaResumo
procedure pNotaChecagem
procedure pNotaProximas
procedure pEstoRecalculo
procedure pupdateexeup
procedure pUtilBackup
procedure pUtilBackupEnvia
procedure pedi0260
procedure pedi0240
procedure psetupempresa
procedure pSiteJPA
procedure pjpforpag
procedure pjpnfbase
procedure pjptransa
procedure pNfeSalvaMysql
procedure pTesEnviaEmail2
procedure pTesEnviaEmail
procedure pnfeImporta
procedure pedi0150
procedure pedicfin
procedure pretitau
procedure pedi0010
procedure pedi0040
procedure pedi0270
procedure pcontimpsped
procedure pfiscsintegra
procedure pjpagenda
procedure pjpcadas1
procedure pjpcadas1b
procedure pjpempre
procedure pcontlancpad
procedure pjplicmov
procedure ljplicmov
procedure pcontcontas
procedure pjpitem
procedure pjpitemb
procedure pjpcadas3
procedure pjpvended
procedure pjppromix
procedure pjpveicul
procedure pjpmotori
procedure pedi0060
procedure pfiscrel0030
procedure pfiscrel0010
procedure pfiscrel0040
procedure pfiscrel0100
procedure pfiscrel0110
procedure pfiscrel0120
procedure pfiscrel0050
procedure ljpforpag
procedure ljpcadas
procedure pjpanpmov
procedure pcontsped
procedure pfiscsped
procedure ljpcadas3
procedure pcontrel0520
procedure pcontrel0210
procedure pcontrel0010
procedure pcontrel0310
procedure pcontrel0320
procedure pcontrel0550
procedure pcontrel0530
procedure pcontrel0385
procedure pcontrel0470
procedure pcontrel0140
procedure pcontrel0080
procedure pleisrelimposto
procedure ljpitem
procedure ljpestoqb
procedure ljpestoqc
procedure pEstoRelAnalise
procedure pjpfisicab
procedure pFinanRelReceber
procedure pFinanRelMaiCli
procedure pFInanRelPagar
procedure pFinanRelMaiFor
procedure pfinanRelFluxo
procedure pcontrel0360
procedure pcontrel0270
procedure pcontrel0380
procedure pcontrel0300
procedure pcontrel0330
procedure pfiscrel0140
procedure pfiscrel0130
procedure pfiscrel0080
procedure pNotaRelRentab
procedure pNotaFicCliVen
procedure pNotaRelNotas
procedure pNotaPlanilhaG
procedure pNotaPlanilhaCV
procedure pNotaPlanilhaC
procedure pNotaRelCliVend
procedure pNotaRelPedRel
procedure pNotaRelMapa
procedure pNotaRelCompMes
procedure pNotaRelCompCli
procedure pNotaRelVendCli
procedure pBancoRelExtrato
procedure pBancoRelSaldo
procedure pBancoRelCCusto
procedure ljpestoqa
procedure pBancoGrafResumo
procedure pFinanEdReceber
procedure pfin0035
procedure pFinanBaixaPort
procedure pcontlancinclui
procedure pcontlanclote
procedure pcontlancaltera
procedure pcontfecha
procedure pcontsintetica
procedure pcontrecalculo
procedure pfiscentradas
procedure pfiscsaidas
procedure pleisimposto
procedure ljppedi
procedure jpacfg
procedure pestolanca2
procedure pestolanca1
procedure pEstoEntFor
procedure pbar0010
procedure pbar0040
procedure pjpfisicaa
procedure pEstoValEst
procedure pEstoTotArmazem
procedure pBancoLanca
procedure pBancoConsolida
procedure pBancoComparaMes
procedure pBancoGraficoMes
procedure pBancoCCusto
procedure pfin0045
procedure pNotaGeraNfe
procedure pda0010
procedure pcteinut
procedure pnfeinut
procedure ppre0010
procedure pPrecoRelTabComb
procedure ppre0020
procedure pPrecoRelTabGeral
procedure pnot0213
procedure pnot0214
procedure pPrecoRelTabMulti
procedure pBancoSaldo
procedure pBancoGera
procedure PFINANEDPAGAR
procedure psetuplibera
procedure p0600ped
procedure pNotaServico
procedure pNotaCadastro
procedure pNotPedRetira
procedure pnotaRomaneio
procedure pjpmdf
procedure pNotaVerVendas
procedure pNotaGeraRps
procedure pcteCancel
procedure ze_netioopen
procedure ze_netioclose
procedure jpnotaclass
procedure jpegBancoItau
procedure UltimaEntradaItem
procedure UltimaSaidaItem
procedure CustoContabilItem
procedure pNotaPedRetira
