/*
ZE_TABMODFIS - MODELOS DE DOCUMENTOS FISCAIS
ULTIMA ATUALIZACAO: 2017.06
*/

FUNCTION ZE_TABMODFIS()

   LOCAL aList := {}

   AAdd( aList, { "01", "NOTA FISCAL" } )
   AAdd( aList, { "1B", "NOTA FISCAL AVULSA" } )
   AAdd( aList, { "02", "NF VENDA A CONSUMIDOR, MODELO 2" } )
   AAdd( aList, { "2D", "CUPOM FISCAL" } )
   AAdd( aList, { "2E", "CUPOM FISCAL BILHETE DE PASSAGEM" } )
   AAdd( aList, { "04", "NF PRODUTOR, MODELO 4" } )
   AAdd( aList, { "06", "NF/CONTA ENERGIA ELETRICA, MODELO 6" } )
   AAdd( aList, { "07", "NF SERVICO DE TRANSPORTE, MODELO 7" } )
   AAdd( aList, { "08", "CONHEC.TRANSP.RODOV.CARGAS, MODELO 8" } )
   AAdd( aList, { "8B", "CONHEC.TRANSP.CARGAS AVULSO" } )
   AAdd( aList, { "09", "CONHEC.TRANSP.AQUAV.CARGAS, MODELO 9" } )
   AAdd( aList, { "10", "CONHEC.AEREO, MODELO 10" } )
   AAdd( aList, { "11", "CONHEC.TRANSP.FERROV.CARGAS, MODELO 11" } )
   AAdd( aList, { "13", "BILHETE PASSAGEM RODOVIARIO, MODELO 13" } )
   AAdd( aList, { "14", "BILHETE PASSAGEM AQUAVIARIO, MODELO 14" } )
   AAdd( aList, { "15", "BILHETE PASSAGEM/NOTA BAGAGEM, MODELO 15" } )
   AAdd( aList, { "16", "BILHETE PASSAGEM FERROV., MODELO 16" } )
   AAdd( aList, { "17", "DESPACHO DE TRANSPORTE, MODELO 17" } )
   AAdd( aList, { "18", "RESUMO DE MOVIMENTO DIARIO, MODELO 18" } )
   AAdd( aList, { "20", "ORDEM DE COLETA DE CARGA, MODELO 20" } )
   AAdd( aList, { "21", "NF SERVICO COMUNICACAO, MODELO 21" } )
   AAdd( aList, { "22", "NF SERVICO TELECOMUNICACAO, MODELO 22" } )
   AAdd( aList, { "23", "GNRE" } )
   AAdd( aList, { "24", "AUTORIZ.CARREGAM/TRANSPORTE, MODELO 24" } )
   AAdd( aList, { "25", "MANIFESTO DE CARGA, MODELO 25" } )
   AAdd( aList, { "26", "CONHEC.TRANSP.MULTIMODAL DE CARGAS" } )
   AAdd( aList, { "27", "NF TRANSP FERROVIARIO DE CARGA" } )
   AAdd( aList, { "28", "NF/CONTA GAS CANALIZADO" } )
   AAdd( aList, { "29", "NF/CONTA DE AGUA CANALIZADA" } )
   AAdd( aList, { "55", "NFE NOTA FISCAL ELETRONICA" } )
   AAdd( aList, { "57", "CTE CONHEC.TRANSP.ELETRONICO" } )
   AAdd( aList, { "59", "CFE CUPOM FISCAL ELETRONICO" } )
   AAdd( aList, { "65", "NFEC NOTA FISCAL ELETRONICA PARA CONSUMIDOR FINAL" } )
   AAdd( aList, { "99", "OUTROS" } )

   RETURN ALIST
