/*
ZE_PISCST _ CST PIS/COFINS
ULTIMA ATUALIZACAO: 2017.06
*/


FUNCTION ZE_TABPISCST()

   LOCAL aList := {}

   AAdd( aList, { "01", "TRIBUTAVEL BC=VALOR DA OPERACAO ALIQ BASICA" } )
   AAdd( aList, { "02", "TRIBUTAVEL BC=VALOR DA OPERACAO ALIQ DIFERENCIADA" } )
   AAdd( aList, { "03", "TRIBUTAVEL BC=QTDE * ALIQUOTA POR UNID PRODUTO" } )
   AAdd( aList, { "04", "TRIBUTAVEL TRIBUTACAO MONOFASICA REVENDA ALIQ ZERO" } )
   AAdd( aList, { "06", "TRIBUTAVEL ALIQUOTA ZERO" } )
   AAdd( aList, { "07", "OPERACAO ISENTA DE CONTRIBUICAO" } )
   AAdd( aList, { "08", "OPERACAO SEM INCIDENCIA DA CONTRIBUICAO" } )
   AAdd( aList, { "09", "OPERACAO COM SUSPENSAO DA CONTRIBUICAO" } )
   AAdd( aList, { "49", "OUTRAS OPERACOES DE SAIDA" } )
   AAdd( aList, { "50", "COM DIREITO A CREDITO - EXCL.RECEITA TRIB INTERNO" } )
   AAdd( aList, { "51", "COM DIREITO A CREDITO - EXCL.RECEITA N.TRIB INTERNO" } )
   AAdd( aList, { "52", "COM DIREITO A CREDITO - EXCL.RECEITA EXPORTACAO" } )
   AAdd( aList, { "53", "COM DIREITO A CREDITO - RECEITAS TRIB E N TRIB INTERNO" } )
   AAdd( aList, { "54", "COM CREDITO - RECEITAS TRIB E N TRIB INTERNO E EXPORT" } )
   AAdd( aList, { "55", "COM CREDITO - RECEITAS N TRIB INTERNO E EXPORT" } )
   AAdd( aList, { "56", "COM CREDITO - RECEITAS TRIB E N TRIB INTERNO E EXPORT" } )
   AAdd( aList, { "60", "CREDITO PRESUMIDO - EXCL.RECEITA TRIB INTERNO" } )
   AAdd( aList, { "61", "CREDITO PRESUMIDO - EXCL.RECEITA N TRIB INTERNO" } )
   AAdd( aList, { "62", "CREDITO PRESUMIDO - EXCL.RECEITA EXPORT" } )
   AAdd( aList, { "63", "CREDITO PRESUMIDO - RECEITAS TRIB.E N TRIB INTERNO" } )
   AAdd( aList, { "64", "CREDITO PRESUMIDO - RECEITAS TRIB. INTERNO E EXPORT" } )
   AAdd( aList, { "65", "CREDITO PRESUMIDO - RECEITAS N TRIB INTERNO E EXPORT" } )
   AAdd( aList, { "66", "CREDITO PRESUMIDO - REC TRIB.E N TRIB INTERNO E EXPORT" } )
   AAdd( aList, { "67", "CREDITO PRESUMIDO - OUTRAS OPERACOES" } )
   AAdd( aList, { "70", "AQUISICAO SEM DIREITO A CREDITO" } )
   AAdd( aList, { "71", "AQUISICAO COM ISENCAO" } )
   AAdd( aList, { "72", "AQUISICAO COM SUSPENSAO" } )
   AAdd( aList, { "73", "AQUISICAO A ALIQUOTA ZERO" } )
   AAdd( aList, { "74", "AQUISICAO SEM INCIDENCIA DA CONTRIBUICAO" } )
   AAdd( aList, { "75", "AQUISICAO POR SUBSTITUICAO TRIBUTARIA" } )
   AAdd( aList, { "98", "OUTRAS OPERACOES DE ENTRADA" } )
   AAdd( aList, { "99", "OUTRAS OPERACOES" } )

   RETURN ALIST
